export const departments = [
  { id: "all", label: "全局", count: 18, tone: "#f0c567" },
  { id: "project", label: "制片", count: 5, tone: "#47d9b2" },
  { id: "director", label: "导演", count: 4, tone: "#ff6b5f" },
  { id: "art", label: "美术", count: 6, tone: "#f0c567" },
  { id: "prompt", label: "提示词", count: 3, tone: "#5ee7df" },
  { id: "video", label: "视频", count: 7, tone: "#77a7ff" },
  { id: "edit", label: "剪辑", count: 4, tone: "#b68cff" },
];

export const stageTabs = ["总览", "镜头", "资产", "生成", "QC"];

export const studioRooms = [
  {
    id: "project",
    name: "总控制片室",
    role: "一句话拆解成全剧任务",
    nodeId: "source",
    state: "自动调度中",
    load: 82,
    x: 42,
    y: 38,
    w: 16,
    h: 18,
    accent: "#47d9b2",
  },
  {
    id: "screenplay",
    name: "编剧室",
    role: "剧本、台词、戏剧节拍",
    nodeId: "script",
    state: "可交接",
    load: 61,
    x: 18,
    y: 14,
    w: 16,
    h: 18,
    accent: "#ffb454",
  },
  {
    id: "director",
    name: "导演室",
    role: "分镜、调度、观众视线",
    nodeId: "director-pack",
    state: "导演复核",
    load: 76,
    x: 64,
    y: 14,
    w: 17,
    h: 18,
    accent: "#ff6b5f",
  },
  {
    id: "art",
    name: "美术资产室",
    role: "角色卡、场景、参考帧",
    nodeId: "asset-master",
    state: "生成中",
    load: 68,
    x: 8,
    y: 62,
    w: 18,
    h: 22,
    accent: "#f0c567",
  },
  {
    id: "prompt",
    name: "提示词工坊",
    role: "图片/视频提示词和负面约束",
    nodeId: "prompt-pack",
    state: "等待上游",
    load: 48,
    x: 30,
    y: 64,
    w: 17,
    h: 20,
    accent: "#5ee7df",
  },
  {
    id: "video",
    name: "本地模型机房",
    role: "ComfyUI / Wan / 云端升级",
    nodeId: "route",
    state: "本地优先",
    load: 72,
    x: 53,
    y: 64,
    w: 18,
    h: 20,
    accent: "#77a7ff",
  },
  {
    id: "edit",
    name: "剪辑与 QC 室",
    role: "候选视频、盲测、交付",
    nodeId: "qc",
    state: "复核中",
    load: 58,
    x: 76,
    y: 62,
    w: 17,
    h: 22,
    accent: "#b68cff",
  },
];

export const automationSteps = [
  { room: "总控制片室", task: "解析一句话目标，创建项目任务树", state: "ready" },
  { room: "导演室", task: "生成镜头包、空间调度、视线闸门", state: "active" },
  { room: "美术资产室", task: "检查角色/场景资产缺口并派发生成", state: "active" },
  { room: "提示词工坊", task: "把导演要求和资产约束转成模型提示词", state: "queued" },
  { room: "本地模型机房", task: "按节点路由调用 ComfyUI 或本地模型", state: "queued" },
  { room: "剪辑与 QC 室", task: "自动盲测、返修、交付版本归档", state: "waiting" },
];

export const localModelRoutes = [
  {
    id: "comfy",
    name: "ComfyUI",
    endpoint: "http://127.0.0.1:8188",
    method: "POST /prompt",
    use: "图片、I2V、FLF2V、工作流 JSON",
  },
  {
    id: "wan",
    name: "Wan 本地服务",
    endpoint: "http://127.0.0.1:7860",
    method: "POST /generate",
    use: "视频生成和批量返修",
  },
  {
    id: "tts",
    name: "TTS / 口型服务",
    endpoint: "http://127.0.0.1:8070",
    method: "POST /speak",
    use: "配音、气口、口型交接",
  },
];


export const gameEvents = [
  { from: "导演", to: "美术", title: "导演镜头包交给美术", state: "进行中" },
  { from: "美术", to: "提示词", title: "角色卡和场景母版进入提示词工坊", state: "排队" },
  { from: "提示词", to: "模型机房", title: "ComfyUI 工作流准备下发", state: "等待" },
  { from: "模型机房", to: "剪辑", title: "候选视频送去盲测 QC", state: "待审" },
];

const node = (id, position, data) => ({
  id,
  type: "studio",
  position,
  data,
});

export const initialNodes = [
  node("source", { x: -720, y: -160 }, {
    department: "project",
    title: "故事原著冻结",
    subtitle: "novel.md / story-bible.md",
    status: "locked",
    owner: "项目办公室",
    accent: "#47d9b2",
    progress: 100,
    eta: "已锁定",
    badges: ["世界观", "人物弧光"],
    checklist: ["主线完整", "人物动机可拍", "禁改项已标记"],
  }),
  node("script", { x: -390, y: -210 }, {
    department: "director",
    title: "编剧分集剧本",
    subtitle: "E01 / G-P 主线",
    status: "ready",
    owner: "编剧部",
    accent: "#ffb454",
    progress: 92,
    eta: "1 处对白复核",
    badges: ["台词", "节奏"],
    checklist: ["对白可配音", "转场可分镜", "冲突节拍明确"],
  }),
  node("director-pack", { x: -60, y: -210 }, {
    department: "director",
    title: "导演镜头包",
    subtitle: "P-01 至 P-05",
    status: "active",
    owner: "导演部",
    accent: "#ff6b5f",
    progress: 78,
    eta: "今日 23:40",
    badges: ["视线", "空间调度", "转场"],
    checklist: ["观众能看懂", "角色方位连续", "镜头动机成立"],
  }),
  node("asset-master", { x: 270, y: -330 }, {
    department: "art",
    title: "美术母资产",
    subtitle: "角色卡 / location master",
    status: "active",
    owner: "美术部",
    accent: "#f0c567",
    progress: 64,
    eta: "2 个场景待补",
    badges: ["角色总卡", "材质板"],
    checklist: ["同脸一致", "透明底合格", "场景锚点固定"],
  }),
  node("prompt-pack", { x: 270, y: -80 }, {
    department: "prompt",
    title: "镜头提示词包",
    subtitle: "六段式镜头 + 负面约束",
    status: "queued",
    owner: "提示词部",
    accent: "#5ee7df",
    progress: 48,
    eta: "等待美术冻结",
    badges: ["首尾帧", "负面词"],
    checklist: ["主体不漂", "镜头不乱转", "动作可执行"],
  }),
  node("voice-cue", { x: 270, y: 170 }, {
    department: "project",
    title: "声音节拍",
    subtitle: "TTS / music cue / 气口",
    status: "ready",
    owner: "配音 + 音乐",
    accent: "#47d9b2",
    progress: 86,
    eta: "可交付",
    badges: ["气口", "音乐 cue"],
    checklist: ["台词时长匹配", "情绪不过载", "口型交接明确"],
  }),
  node("route", { x: 640, y: -80 }, {
    department: "video",
    title: "模型路由",
    subtitle: "本地 Wan 优先 / 云端升级",
    status: "active",
    owner: "视频生成部",
    accent: "#77a7ff",
    progress: 71,
    eta: "预算正常",
    badges: ["Wan", "云模型", "失败根因"],
    checklist: ["低成本先跑", "两轮失败升级", "保留失败样本"],
  }),
  node("render", { x: 980, y: -190 }, {
    department: "video",
    title: "候选视频生成",
    subtitle: "P-01-v0216 批量",
    status: "risk",
    owner: "视频生成部",
    accent: "#77a7ff",
    progress: 42,
    eta: "2 个镜头返修",
    badges: ["I2V", "FLF2V"],
    checklist: ["人物不变脸", "动作不跳帧", "镜头方向正确"],
  }),
  node("qc", { x: 980, y: 80 }, {
    department: "edit",
    title: "盲测 QC",
    subtitle: "看懂 / 稳定 / 表演",
    status: "review",
    owner: "导演 + 剪辑",
    accent: "#b68cff",
    progress: 58,
    eta: "需导演复核",
    badges: ["观众盲测", "字幕"],
    checklist: ["因果能懂", "转场连续", "字幕不遮挡"],
  }),
  node("delivery", { x: 1320, y: -40 }, {
    department: "edit",
    title: "成片交付",
    subtitle: "01.mp4 / 归档 / 发布闸门",
    status: "waiting",
    owner: "交付部",
    accent: "#f0c567",
    progress: 26,
    eta: "等待 QC 通过",
    badges: ["4K", "归档"],
    checklist: ["码率合格", "音画同步", "版本索引完整"],
  }),
];

export const initialEdges = [
  { id: "e-source-script", source: "source", target: "script", animated: false },
  { id: "e-script-director", source: "script", target: "director-pack", animated: false },
  { id: "e-director-art", source: "director-pack", target: "asset-master", animated: true },
  { id: "e-director-prompt", source: "director-pack", target: "prompt-pack", animated: true },
  { id: "e-art-prompt", source: "asset-master", target: "prompt-pack", animated: true },
  { id: "e-prompt-route", source: "prompt-pack", target: "route", animated: true },
  { id: "e-voice-route", source: "voice-cue", target: "route", animated: false },
  { id: "e-route-render", source: "route", target: "render", animated: true },
  { id: "e-render-qc", source: "render", target: "qc", animated: true },
  { id: "e-qc-delivery", source: "qc", target: "delivery", animated: false },
];

export const queue = [
  { id: "ART-L002-PACK", title: "山道难民沟场景母版", owner: "美术", state: "制作中", risk: "中" },
  { id: "PROMPT-P03-v001", title: "P-03 镜头提示词拆分", owner: "提示词", state: "等待上游", risk: "低" },
  { id: "VIDEO-P01-v0216", title: "P-01 本地 Wan 返修测试", owner: "视频", state: "QC", risk: "高" },
  { id: "EDIT-GP-v0003", title: "G-P 五镜头节奏版", owner: "剪辑", state: "待剪", risk: "中" },
];

export const versions = [
  { id: "P-01", version: "v0216", state: "生成中", score: 72 },
  { id: "P-02", version: "v0008", state: "通过", score: 91 },
  { id: "P-03", version: "v0012", state: "返修", score: 58 },
  { id: "P-04", version: "v0005", state: "待声画", score: 66 },
  { id: "P-05", version: "v0007", state: "通过", score: 88 },
];

export const logs = [
  "导演部更新 P-01 空间调度说明",
  "美术部冻结 C024 军户群像模板",
  "视频部记录 v0215 失败根因：主体漂移",
  "剪辑部提交 G-P 预览版 QC 摘要",
];

export const vault = [
  "project-memory.md",
  "asset-index.json",
  "P-01-spatial-camera-plan.md",
  "timing-manifest.json",
  "music-sfx-handoff.md",
];

